#!/usr/bin/env python

import sys
import subprocess
import h5py

input = sys.argv[1]
output = sys.argv[2]

f = h5py.File(input, 'r')
coord_type = f['Grid']['Geometry']['Walls 1'].dtype.names[0]

if coord_type == 'w':
    p = subprocess.call('hyperion_cyl %s %s' % (input, output), shell=True)
elif coord_type == 'r':
    p = subprocess.call('hyperion_sph %s %s' % (input, output), shell=True)
elif coord_type == 'x':
    p = subprocess.call('hyperion_car %s %s' % (input, output), shell=True)
else:
    raise Exception("Unexpected coordinate type: %s" % coord_type)
    
