#!/usr/bin/env python

import sys

import h5py
import pyfits
import numpy as np


for filename in sys.argv[1:]:

    f = h5py.File(filename)
    n_groups = len(f['Peeled'])
    for ig in range(n_groups):
        group = f['Peeled/Group %05i' % (ig + 1)]
        if 'images' in group:
            image = group['images']
            pyfits.writeto(filename.replace('.rtout', '_images.fits'),
                           np.array(image), clobber=True)
