#!/usr/bin/env python

import sys

from hyperion.model import TtsreModel

def _usage(*args):
    print 'Usage: ttsre2rtin input output'
    
if len(sys.argv) <> 3:
    _usage()

dens_file = pyfits.open(sys.argv[1] + '/darr.fits.gz')

r_wall = dens_file[1].data.field('r walls').astype(np.float64)
t_wall = dens_file[2].data.field('theta walls').astype(np.float64)
p_wall = dens_file[3].data.field('phi walls').astype(np.float64)

m = TtsreModel(sys.argv[2])
m.load_from_mctherm(sys.argv[1] + '/mctherm.par')
m.set_polar_grid(r_wall, t_wall, p_wall)
m.write()