#!/usr/bin/env python

import sys

from hyperion.model import TtsreModel

def _usage(*args):
    print 'Usage: ttsre2rtin input output'
    
if len(sys.argv) <> 3:
    _usage()

m = TtsreModel(sys.argv[2])
m.load_from_mctherm(sys.argv[1] + '/mctherm.par')
m.set_polar_grid_auto(m.nr, m.nt, m.np)
m.write()
